### ISSUE TITLE
Script Sometimes Crashes during Plex Server Reboot

### ISSUE THREAD

**Issue by MoeFwacky** [justinemter/pseudo-channel#14]
My server goes down for reboot at 5:05am each day. I've noticed a couple of times that the script will have crashed around that time as well, but it's not 100%. I haven't been able to track it yet, but I believe it happens when the script attempts to play something at a time when the server is unreachable. When the server doesn't crash is usually when something is already playing, meaning the script didn't attempt to play something new at that time. 

An easy fix for this, and maybe something desirable anyway, might be to include a user-defined range of time in the config or schedule xml/gcal in which commercials can't be injected. This might be a good idea anyway for anybody who has scheduled reboots or doesn't want to inject commercials into 'off-air' hours.

**Comment by justinemter** [comment]
> to include a user-defined range of time in the config or schedule xml/gcal in which commercials can't be injected

This is a great idea. As of now though the script doesn't inject commercials before the first scheduled show of the day... funnily I did not write logic for this but somehow it defaulted to that behavior.
