### ISSUE TITLE
Some items scheduled close with other items fail to play

### ISSUE THREAD

**Issue by MoeFwacky** [justinemter/pseudo-channel#16]
In my observations, when two items (usually commercials, but sometimes a show or movie) are scheduled to start in the same minute (usually due to a commercial being under a minute long), the script doesn't fire off the second item. In at least one case with three items in the same minute, the first played, the second failed and the third played. So far, I've observed this with the first item being a commercial of as much as 30 seconds.

edit: after some further observation, it looks like it's not necessary that they be in the same minute to fail, but it appears to happen with items that start within about 30 seconds of each other. This is likely related to me running the server on a raspberry pi and longer load times (give or take about 10 seconds from when the script reports it's starting to the beginning of playback.

edit 2: had a failure to play back on a first (strict time on) item of the schedule. there had been a gap in playback after I manually rebuild the schedule for the day due to Issue #17. Not sure what caused the failure, but the terminal output didn't show any playback attempt

**Comment by justinemter** [comment]
Hmm, I have tested this thoroughly on my setup and haven't encountered it. I'm going to mark this as closed as it is most likely due to the pi setup. I'll add an enhancement "issue" to figure out a way to cater to smaller embedded devices like the pi.
