### ISSUE TITLE
Daily schedule rebuild builds the same schedule as yesterday

### ISSUE THREAD

**Issue by MoeFwacky** [justinemter/pseudo-channel#17]
Using -xml, the daily schedule refresh went off at 12:01, but it just did another run of the previous day's schedule instead of the day it should have been. On Sunday at 12:01 it recreated the saturday schedule, and did the same the next day with the Sunday schedule on Monday at 12:01 (after I re-ran the script to get the right schedule for Sunday).

**Comment by justinemter** [comment]
I think I may know the solution to this one. Good eye!
