### ISSUE TITLE
Socket Error on OS X

### ISSUE THREAD

**Issue by irodimus** [justinemter/pseudo-channel#23]
Attempting to run Pseudo-Channel on OS X gives this: 

```
Traceback (most recent call last):
  File "PseudoChannel.py", line 912, in <module>
    pseudo_channel = PseudoChannel()
  File "PseudoChannel.py", line 62, in __init__
    self.DEBUG
  File "/Applications/pseudo-channel/src/PseudoDailyScheduleController.py", line 31, in __init__
    self.handler = logging.handlers.SysLogHandler(address = '/dev/log')
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 761, in __init__
    self._connect_unixsocket(address)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 789, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory
```

According to the Python Docs when using the SysLogHandler class, the domain socket address OS X uses is ‘/var/run/syslog’ instead of '/dev/log'.

Changing line 31, in 'pseudo-channel/src/PseudoDailyScheduleController.py' to reflect this does allow the program to continue. According to the docs, this is system dependent and would require a platform check.

**Comment by justinemter** [comment]
Interesting! Yes it is built to run on a raspberry pi. There is however very little code that makes it platform dependent... that there and also a small time formatting issue that throws an err on my windows machine. After knocking out the bigger issues I'll try and test it on other platforms cause why not. If you wanted to play around with it now, I recommend grabbing the develop branch and commenting out the logging stuff.

**Comment by irodimus** [comment]
I will try the development branch and see how that goes. It took a while to get up and running as the instructions say one thing about creating a  'pseudo_config.py' but the instructions from within your file 'pseudo_config.py' file say something else about creating a 'plex_token.py'.

I was running the script from my Mac running PMS, connecting to a client Pi3. It hasn't worked yet but it could just be my setup, which I'm still messing with. Does the video resume at whatever time you run the pseudo-channel program (mid movie or tv show) or does it only start at the designated times?

**Comment by justinemter** [comment]
The file name thing is my fault...typo, I'll fix that. I am doing it like that so I keep private creds out of the repo. It's an unfortunate extra step that adds to the complexity. I'm wondering if maybe it's your mac & her pms that might be causing issues? Maybe waiting a few days til she comes around? ;) (terrible joke, sorry)

How it works is really simple, it just takes in the xml to understand how to automatically generate a daily schedule... the "time-shift" feature is really cool but makes it more complicated than it needs to be. Then at "12:00 AM" everyday after the schedule is made, a python library called "schedule" is used to set triggers for the designated times to start the media. It's like a cron task that just fires of the play() function as it was saved in the "daily_schedule" table in the sqlite db. It's incredible how much code it has taken to get to this point as the idea still is so simple!

**Comment by irodimus** [comment]
I see. So if the video is already in progress, it doesn't resume and just waits for the next start time? If it does, maybe I just haven't waited for that to happen.

**Comment by justinemter** [comment]
> So if the video is already in progress, it doesn't resume and just waits for the next start time? If it does, maybe I just haven't waited for that to happen.

Yes, I think. Basically, it's supposed to be setup once and set free to run forever (or as long as you want)...advancing forward every day in the "pseudo queue", playing your scheduled sitcoms / random movies. That being said you should use a raspberry pi running RasPlex specifically for your pseudo channel on say, HDMI port 3. So whenever you're tired of thinking of what to watch on Netflix and want to just see what's on your channel, you flip your tv to HDMI 3 and there it is running. It's not the most power efficient solution no. But it's actually pretty neat when it's running...the commercial injection thing is pretty funny, especially when using a bunch of old 90's commercials. I think it would be good for parties in the background too. 

> Thanks for attempting to fill in a "PseudoTV"-type ability for Plex :)

Glad there are more of us with this particular "need". Cheers! :)
