### ISSUE TITLE
Error when leaving WebServer details empty

### ISSUE THREAD

**Issue by irodimus** [justinemter/pseudo-channel#25]
Using latest commit 5b91f7b670b2a1d1ca1d8222bc33add451cb2d41 on master, if you leave WebServer detail empty in 'pseudo_config.py'

```
controllerServerPath = ""
controllerServerPort = ""
```
you get this error:

```
Traceback (most recent call last):
  File "PseudoChannel.py", line 1033, in <module>
    pseudo_channel.generate_daily_schedule()
  File "PseudoChannel.py", line 832, in generate_daily_schedule
    self.make_xml_schedule()
  File "PseudoChannel.py", line 857, in make_xml_schedule
    self.controller.make_xml_schedule(self.db.get_daily_schedule())
  File "/Applications/pseudo-channel/src/PseudoDailyScheduleController.py", line 715, in make_xml_schedule
    self.write_schedule_to_file(self.get_html_from_daily_schedule(None, None, datalist))
  File "/Applications/pseudo-channel/src/PseudoDailyScheduleController.py", line 394, in write_schedule_to_file
    self.start_server()
  File "/Applications/pseudo-channel/src/PseudoDailyScheduleController.py", line 91, in start_server
    PORT = int(self.CONTROLLER_SERVER_PORT)
ValueError: invalid literal for int() with base 10: ''
```

Hoping I didn't misunderstand leaving that empty like that or inserting 0.0.0.0 or 127.0.0.1 or something. If you do put in an IP, it will continue though, but I don't need it to.

**Comment by justinemter** [comment]
Oh you know what, I am allowing the user to leave the IP field empty but not the Port. I added all that webserver stuff quickly as an after thought so am really happy you're finding this. I'll fix it. :)

**Comment by irodimus** [comment]
Is there a way to create the schedules folder elsewhere? I have a web server running already and I can just move the schedules folder but if it can save it there is an option where the folder can be created or updated instead, that would be great.

**Comment by justinemter** [comment]
I just pushed to the develop branch. You may want to stick with that branch as I make these quick edits. :)

**Comment by justinemter** [comment]
> Is there a way to create the schedules folder elsewhere?

No need, just create a "symbolic link" anywhere you want, like so: "ln -s /home/pi/pseudo-channel/schedules/ /var/www/html/pseudo-channel/"

You have to create the directory 'pseudo-channel' in your apache first and that symbolic line will make apache think that all the contents in the 'schedules' dir are in the apache dir. Unix is rad.
