### ISSUE TITLE
[Feature Request] Resume video when PseudoChannel is started

### ISSUE THREAD

**Issue by irodimus** [justinemter/pseudo-channel#30]
I'm not sure if the option is available using Plex API as I've looked at it briefly, but is there a way to resume a video when a schedule has been generated and the the PseudoChannel program is started? I guess this is more to verify the program is working just cause there are instances where there is an issue with the schedule and PseudoChannel is required to manually shutdown and restart. Nothing really happens until the next scheduled start time. Most of the times, the videos, or in my case movies, tend to start 30 min or hour later no matter how many times I generate new schedules. Not entirely necessary but to have a video playing mid movie according to the time difference from start time would be neat instead of waiting. I hope that makes sense.

**Comment by justinemter** [comment]
I see what you mean [I think]. So basically if you run "python PseudoChannel.py -r" at "2:30 PM" and a movie just started like 10 minutes prior, have the app start the movie and seek to 10 or whatever minutes in - exactly where it was supposed to be playing if it were running? If I am understanding you correctly then this is entirely possible. In fact, I was thinking of implementing a power-saving option where I somehow get whether or not the user has switched to say, HDMI 3 or pressed a certain button on their remote and the app starts playing the schedule whenever it is supposed to within the time the button was pressed. Then when the TV is turned off or the button is pressed again it stops play back (but the 'virtual queue' still moves forward as usual). I don't like the idea of my server playing content even when the tv is off... although at my house this is rare. Anyway, I think your use case should be rare (outside of testing) so probably won't focus on that. However if I do implement the power-save feature then it should work with wiring up an external trigger (button, Amazon echo voice trigger, etc.).

**Comment by irodimus** [comment]
Yes, just when the program starts is what I was suggesting, to look at what point it was and resume from there instead of waiting for the next start time. Right now, nothing plays till then if the start time is missed.

**Comment by justinemter** [comment]
Right, that's because the app is currently programmed to triggered to play when it was scheduled and then sleeps for a while. So yeah if you run it half way through a scheduled item it sleeps until the next startTime trigger. I'll totally implement the power saving feature which can be hooked up to a python flag "--check-start" or something that can be used for your use case or power-saving mode. Keep in mind that this program is made to be run once and forgotten about. :)

**Comment by irodimus** [comment]
I totally get that, but right now, just running into an issue where the next time the schedule is supposed to be created, Only one movie is listed, but I don't know why till I get home from work the next day. I stop PseudoChannel, generate a new schedule, and restart the app manually. Then I wait for the next schedule start time :( I made it output to a file next time so I can see what errors it's getting and pass them along.

**Comment by justinemter** [comment]
Ok, I'll implement it now. Well I'll try to just implement a function that checks to see what should be playing when the program starts and triggers it at the correct position. This should help you debug any issues. Also make sure you got the most recent push to 'develop'.

**Comment by irodimus** [comment]
Will do. Hopefully tomorrow, I'll also have a log as to why the next day schedule only generates with one movie :)

**Comment by justinemter** [comment]
Ok try that.

**Comment by irodimus** [comment]
Tested and works perfectly so far! That is awesome. And the web page updates too :) Really, appreciate this as I wasn't sure how possible it was. I'll keep this running and report if any issues come up.

**Comment by justinemter** [comment]
Good to hear! Great idea too, didn't realize I needed this until putting it in.

**Comment by irodimus** [comment]
I messed with this function a bit more and I run into this issue but am not sure why. When starting PseudoChannel, there are instances where it hangs after the Here information is displayed. The first time it occurred, I was able to restart my Pi3 and it resolved it. But lately it's become more frequent. Generally to test, I've escaped the program with Control-C and then stopped the playback on the Pi. I'm not sure if there is something else occurring that I may have messed up somewhere by doing this, but there is not a lot of information showing. 

One interesting thing was that even though it did not resume and stayed "hanging" there, the next  start time did fire and play the next video.

**Comment by justinemter** [comment]
Ok so right now what's happening is it it's outputting the next closest media Item. Check the title in the output and see if it is trying to play the current media or the upcoming. The function dismisses the play() function because it sees the upcoming item as the next item and dismisses the previous item (which is still the current item). arrg, I'm working on a fix.

**Comment by irodimus** [comment]
Oh, wow, I just noticed that. Didn't realize that it was selecting the next movie to play :) I did try the latest commit that may include the potential fix to test but it still happens in case you were wondering.

**Comment by justinemter** [comment]
Ok I think I fixed it buut I believe if you run it during a gap in the schedule or if you run it at the end of the night when nothing more is scheduled, it may just try and trigger the previous media item + elapsedTime... this would result in the app trying to queue up a media item and seek to a spot past its end-time... I have the play function fail silently so am betting nothing will happen but it's possible it will default to playing the last media item from the beginning or something weird. We'll see. :)

**Comment by justinemter** [comment]
> I did try the latest commit that may include the 1st potential fix to test but it still happens in case you were wondering.

Sorry just got this. Ok cool I did just commit like right when you commented so am hoping that does it.

**Comment by irodimus** [comment]
Luckily, I had a video that would not play and go straight to "Not starting any media." Without generating a new schedule and pulling the new commit, I started up Pseudo Channel and it resumed playing the video file  :)

**Comment by justinemter** [comment]
Good to hear! Also I commit a lot because it's the quickest way for me to test on my pi (without using sublime text ssh).

**Comment by irodimus** [comment]
I'm kinda glad this feature works very well because it can open up some possibilities in a future Plex Channel. I'm not sure how possible it is because I don't code Python, just some bash scripting and can follow some code here and there, so you probably have a better idea on how possible it could be since you seem better versed in it.

**Comment by justinemter** [comment]
Me too man! If you think about it, once this feature is bug free / tested, you could hook up a button to your pi that triggers a bash script to run PseudoChannel -r... this would be akin to flipping to your channel. When you're done and want to "turn off your channel" you can have another bash function trigger it to kill the running app when the button is pressed. This could be triggered by anything, clap on / clap off, farting, or of course your remote with a simple IR Led hooked up to your pi or an arduino. So we just inadvertently added some of the best features in my opinion. The power saving / wear on your Plex media hard drives too. I hate the thought of my channel running all day without anyone watching it. This way it still runs but in conceptual form, waiting to be turned on / queued up.

**Comment by irodimus** [comment]
Yep, exactly what I was thinking! The two main things was 1) generating the schedules and 2) the ability to resume the video and kill the app when exiting. If you've ever used the HDHR Viewer channel plugin, the GUI it uses to display the channels works fine for most cases, mostly rows and not a guide. It would just be a matter of reading and displaying several "channels" in that form and running PseudoChannel.py -r when clicking on it. Escaping kills the stream and exits back to the "guide." The channel can handle the updating of reading the current schedule and updating when neccessary. Again, just throwing ideas out there.

**Comment by justinemter** [comment]
Ok I think the daily schedule error is fixed, or at least this particular one where it only added 1 item to the schedule. I also added a "pseudo-channel.log" file that should be generated in the current pseudo-channel/ folder. It should help more with debugging, especially if using './startstop.sh'. Also be sure to use 'tail -f ./pseudo-channel.log' to watch log entries get appended in real time. You need to have two terminals for that (or use tmux or screen or something similar). Cheers!
