### ISSUE TITLE
Generating new schedule and then running Pseudo Channel selects last movie in list

### ISSUE THREAD

**Issue by irodimus** [justinemter/pseudo-channel#32]
This is something I noticed after a new schedule was generated manually on the develop branch, commit 1e7219cb7069623e05b7a0fd833d82c810341dca. Manually generated a new schedule at 12:42AM:

```
+++++ 1. 12:00:00 AM Movies   -  Taken 2
+++++ 2. 01:40:00 AM Movies   -  Saw
+++++ 3. 03:25:00 AM Movies   -  The Matrix Reloaded
+++++ 4. 05:45:00 AM Movies   -  Private Benjamin
+++++ 5. 07:35:00 AM Movies   -  Kabluey
+++++ 6. 09:05:00 AM Movies   -  Village of the Damned
+++++ 7. 10:45:00 AM Movies   -  D2: The Mighty Ducks
+++++ 8. 12:35:00 PM Movies   -  Iron Man
+++++ 9. 02:45:00 PM Movies   -  A Nightmare on Elm Street Part 2: Freddy's Revenge
+++++ 10. 04:15:00 PM Movies   -  Happy Gilmore
+++++ 11. 05:50:00 PM Movies   -  Lost in America
+++++ 12. 07:25:00 PM Movies   -  The Unborn
+++++ 13. 08:55:00 PM Movies   -  Gone Baby Gone
+++++ 14. 10:50:00 PM Movies   -  The Wisdom of Crocodiles
+++++ 15. 12:30:00 AM Movies   -  The Big Kahuna
```

Started up Pseudo Channel and it resumed with The Big Kahuna at the bottom instead of Taken 2 at the top. It's possible due to date not being fully implemented as it appears to go just on time currently, but I wanted to make sure I was doing something wrong.

Also, when a new schedule is generated, am I correct that it does not currently append to the schedule and it's normal for the movie playing to be stopped and the new video plays?

**Comment by justinemter** [comment]
> Started up Pseudo Channel and it resumed with The Big Kahuna at the bottom instead of Taken 2 at the top. It's possible due to date not being fully implemented as it appears to go just on time currently, but I wanted to make sure I was doing something wrong.

hmm, I'll see what I can do.

> Also, when a new schedule is generated, am I correct that it does not currently append to the schedule and it's normal for the movie playing to be stopped and the new video plays?

The original idea was to start the app once, and forget it. Every day it generates a new schedule - this new schedule not interrupting whatever was finishing playing. Last night I implemented this new power saving feature which seems to work outside that touchy time. I'll have to mark this as an enhancement.

**Comment by irodimus** [comment]
No problem. I understand the resume feature is still work in progress. Just wanted to report any observations.

> The original idea was to start the app once, and forget it. Every day it generates a new schedule - this new schedule not interrupting whatever was finishing playing. Last night I implemented this new power saving feature which seems to work outside that touchy time. I'll have to mark this as an enhancement.

I was watching a movie that was playing and around the time it created a new schedule, without my intervention, it just stopped it and started the new movie in the newly created schedule. No big deal. Just curious. I'm sure I can set the time to generate a new schedule in the early morning when I'm not watching anything to get by.

**Comment by justinemter** [comment]
> I was watching a movie that was playing and around the time it created a new schedule, without my intervention, it just stopped it and started the new movie in the newly created schedule. No big deal. Just curious. I'm sure I can set the time to generate a new schedule in the early morning when I'm not watching anything to get by.

Hmm, let me tinker with it tomorrow. I think I know a solution but have to toy with it a bit. I use pseudo-channel almost entirely for sitcoms that end before 11 so your use-case is interesting. I'll have something figured out soon. I appreciate your feedback. Check back tomorow.

**Comment by justinemter** [comment]
> I was watching a movie that was playing and around the time it created a new schedule, without my intervention, it just stopped it and started the new movie in the newly created schedule. No big deal. Just curious. I'm sure I can set the time to generate a new schedule in the early morning when I'm not watching anything to get by.

Ok, so I added some logic to "cache" the previous days' schedule... when the the update happens (at midnight) it will consult the cached schedule before creating the in-memory "schedule" to determine if it should schedule the new item. The focus for this logic is to put emphasis on the time the app updates and disregard any media that is trying to interrupt the playback of whatever you are previously watching. If you start the app just after the update at midnight and a movie started at 11:30 PM, you will not be watching the previous scheduled movie but whatever the new schedule generated. However, if you had the app running and the movie started at 11:30 PM, the new logic will hopefully dismiss any play() triggers until that movie ends.

**Comment by irodimus** [comment]
Will give it a look today 👍

**Comment by irodimus** [comment]
So, after updating to the latest commit and letting PseudoChannel run without intervention, I went from this:

```
plex-ht:pseudo-channel administrator$ python PseudoChannel.py -s
##### Daily Pseudo Schedule:
##### Getting Daily Schedule from DB.
+++++ Done.
+++++ 1. 12:00:00 AM Movies   -  Jury Duty
+++++ 2. 01:30:00 AM Movies   -  El Cid
+++++ 3. 04:40:00 AM Movies   -  Triple 9
+++++ 4. 06:40:00 AM Movies   -  Nacho Libre
+++++ 5. 08:15:00 AM Movies   -  Night of the Creeps
+++++ 6. 09:45:00 AM Movies   -  Despicable Me
+++++ 7. 11:20:00 AM Movies   -  D3: The Mighty Ducks
+++++ 8. 01:05:00 PM Movies   -  Term Life
+++++ 9. 02:40:00 PM Movies   -  The Bridges of Madison County
+++++ 10. 04:55:00 PM Movies   -  Bad Moon
+++++ 11. 06:15:00 PM Movies   -  Mandela: Long Walk to Freedom
+++++ 12. 08:40:00 PM Movies   -  He's Just Not That Into You
+++++ 13. 10:50:00 PM Movies   -  The Avengers
+++++ 14. 01:15:00 AM Movies   -  My Best Friend's Wedding
+++++ 15. 03:00:00 AM Movies   -  Powder
```

to 

```
plex-ht:pseudo-channel administrator$ python PseudoChannel.py -s
##### Daily Pseudo Schedule:
##### Getting Daily Schedule from DB.
+++++ Done.
+++++ 1. 12:00:00 AM Movies   -  Jury Duty
+++++ 2. 01:30:00 AM Movies   -  El Cid
+++++ 3. 04:40:00 AM Movies   -  Triple 9
+++++ 4. 06:40:00 AM Movies   -  Nacho Libre
+++++ 5. 08:15:00 AM Movies   -  Night of the Creeps
+++++ 6. 09:45:00 AM Movies   -  Despicable Me
+++++ 7. 11:20:00 AM Movies   -  D3: The Mighty Ducks
+++++ 8. 01:05:00 PM Movies   -  Term Life
+++++ 9. 02:40:00 PM Movies   -  The Bridges of Madison County
+++++ 10. 04:55:00 PM Movies   -  Bad Moon
+++++ 11. 06:15:00 PM Movies   -  Mandela: Long Walk to Freedom
+++++ 12. 08:40:00 PM Movies   -  He's Just Not That Into You
+++++ 13. 10:50:00 PM Movies   -  The Avengers
+++++ 14. 01:15:00 AM Movies   -  My Best Friend's Wedding
+++++ 15. 03:00:00 AM Movies   -  Powder
+++++ 16. 04:55:00 AM Movies   -  The Hot Spot
+++++ 17. 07:10:00 AM Movies   -  Dragonball Evolution
+++++ 18. 08:40:00 AM Movies   -  Daddy Day Care
+++++ 19. 10:15:00 AM Movies   -  Toy Story 2
+++++ 20. 11:50:00 AM Movies   -  Die, Monster, Die!
+++++ 21. 01:10:00 PM Movies   -  Ejecta
+++++ 22. 02:35:00 PM Movies   -  Sing
+++++ 23. 04:25:00 PM Movies   -  The Accused
+++++ 24. 06:20:00 PM Movies   -  Blade: Trinity
+++++ 25. 08:15:00 PM Movies   -  Royal Deceit
+++++ 26. 10:05:00 PM Movies   -  Employee of the Month
+++++ 27. 11:55:00 PM Movies   -  For Your Eyes Only
+++++ 28. 02:05:00 AM Movies   -  School Daze
+++++ 29. 04:05:00 AM Movies   -  Alive
+++++ 30. 06:10:00 AM Movies   -  Doom
```

Looks like on schedule generation at 12AM, it tacked on the next schedule, but at the same time, appeared to start showing the video from the top of the list. At the time, It looks like The Avengers was still showing.

**Comment by justinemter** [comment]
It looks like that first issue, the one where the DB isn't flushing out the previous schedule is one others have experienced. I haven't so it's difficult to know exactly what is causing it. I'm going to try and adjust things so it avoids bottlenecking - if that is the root of the problem. 

Not sure about your second issue, can you help me understand it a little more?

**Comment by irodimus** [comment]
There's this weird thing going on right now where I had manually ran PseudoChannel.py -g after this issue occurred to generate a new schedule, which was confirmed by running PseudoChannel -s and looking at the HTML. The new schedule was generated but when it came to playing the next video, PseudoChannel appeared to revert to the old schedule and also displayed it in the HTML. On top of that the new schedule still displayed when running PseudoChannel -s but appeared to be ignored. 

It must have been been caused by a specific set of event I can't replicate right now as I just went ahead and restarted PseudoChannel and generated a new schedule. I will look out for this and report back.

**Comment by irodimus** [comment]
This has been working without problems for the past few days.

**Comment by justinemter** [comment]
I highly recommend giving commercials a shot! I thought the novelty would wear off but it's actually really cool. Use [youtube-dl](https://rg3.github.io/youtube-dl/download.html) to download commercials from you tube. Then create a library in plex called "Commercials". There is an option in the docs where you can use youtube-dl to download entire playlists...and if you search youtube for like, "classic commercials" or "90's commercials" or "90's movie trailers" you'll find playlists with like hundreds of commercials. The more the better - not only for variety but the algorithm injects commercials to fill up gaps between media so the more commercials the more the varies commercial durations exist for the app to use. Anyway, give it a shot if you want. Cheers! :)

**Comment by MoeFwacky** [comment]
To jump on the commercials thing, I agree you should try it out and I have about 300 commercials on [my channel](https://www.youtube.com/channel/UC5NMg5wuKkNJzhhj8z6hxhA) you can grab. Feel free to download the lot and give it a try.

**Comment by justinemter** [comment]
Thanks moe! Sorry I should've linked your channel :)

**Comment by irodimus** [comment]
I will take a look at those. Thanks!
