### ISSUE TITLE
script not scanning additional libraries to database

### ISSUE THREAD

**Issue by MoeFwacky** [justinemter/pseudo-channel#36]
The config has an entry for a "Music" library, which I configured to point to my "Music Videos" library, but it doesn't appear to scan with `-u`. I'm not sure if this is a bug, or just hasn't been hooked up yet.

**Comment by justinemter** [comment]
It's not hooked up yet. In reality, I need to make that functionality more blind to what it's doing. Right now I've really built the whole thing to assume that you have TV Shows and Movies at the very least. I remember adding music but can't remember where I ended up with that / why I'm not adding it to the DB. I'll put this on the list for beta.
