### ISSUE TITLE
Using multiple libraries?

### ISSUE THREAD

**Issue by irodimus** [justinemter/pseudo-channel#42]
Is there a current option when specifying the title of the libraries in pseudo_config.py to use more than one library for the same type of media?

```
plexLibraries = {
    "TV Shows" : ["TV Shows"],
    "Movies"   : ["Movies"],
    "Music"    : ["Music"],
    "Commercials" : ["Commercials"],
}
```

If I have a library called "Movies" and another library called "Kids Movies", can I use both?

**Comment by justinemter** [comment]
As of now, no. This too will be something I'll implement in the next release. Moe over at FakeTV, also has big ideas of using custom libraries for all sorts of creative use-cases. I hope to have that stuff working soon. :)
