### ISSUE TITLE
Synopsis on web page schedule

### ISSUE THREAD

**Issue by irodimus** [justinemter/pseudo-channel#43]
Would it be possible to show the synopsis for the tv show episode or the movie on the webpage?

**Comment by justinemter** [comment]
Yeah for sure. Also, if you do choose to use commercials be sure to set debug to False in the config. It fills up the html schedule with commercials.

**Comment by justinemter** [comment]
So I don't want to spend too much time on that html schedule. However, one thing I can try and accomplish is to link each movie/episode to their respective IMDB pages. That way I don't have to fidget with the spacing, etc. and it can just open a new tab. Tell me what you think.
