### ISSUE TITLE
Episodes not advancing

### ISSUE THREAD

**Issue by MoeFwacky** [justinemter/pseudo-channel#44]
It's taken a few days of observing to be sure, but it looks like shows are not advancing episodes ahead with each new day's schedule. I updated from the develop branch late last night.

**Comment by justinemter** [comment]
Hmm, it should be working. Did you delete the db / run "-u" again following the new import / export features? The newest update to develop requires you to create a fresh database (I changed some things).

**Comment by MoeFwacky** [comment]
Yeah I did a -e, created a new database with -u and ran -i last night. I'm not sure if it's every show or just some, but the same episode of Fresh Prince that played last week just played. I'll keep an eye out tonight and see if I notice anything else being off.

**Comment by MoeFwacky** [comment]
Looks like three episodes tonight are repeating last week. It's possible I restored an old backup of the database some time in the last week. I'll keep watching to see what changes, but it will take a bit since my new schedule doesn't have a lot of shows that repeat more than once or twice a week.

**Comment by MoeFwacky** [comment]
Just hit another show that did advance from the past episode, so for now, I'm betting this was a database backup and restore issue from last week probably. I'll keep keeping my eye out going forward, but I'll close this since it's looking likely this is a problem on my end and not with the script.
