### ISSUE TITLE
Variant to -g that doesn't advance episodes

### ISSUE THREAD

**Issue by MoeFwacky** [justinemter/pseudo-channel#62]
As per the discord discussion.

If I backup episode positions today, and delete and rescan the database, then import the positions and generate a schedule, it will skip the episodes originally scheduled for today and advance to the next ones.

This request is for a variant of -g that allows the regeneration of today's schedule by not advancing to the next episodes.

**Comment by justinemter** [comment]
I think the newer "-eds" and "-ids" solves this.
