### ISSUE TITLE
Same commercial played twice in a row, second playback not on schedule

### ISSUE THREAD

**Issue by MoeFwacky** [justinemter/pseudo-channel#63]
I was watching today when I noticed the same commercial play twice in a row. I checked the schedule to see if they had been scheduled and they hadn't. The next commercial up was a music video, so it left a bit of a gap in playback until i restarted the channel. 

Schedule from -s
```
+++++ 1. 12:00:00 AM TV Shows The Boondocks  -  The Itis
+++++ 2. 12:19:51 AM Commercials   -  subaru-justy-1987
+++++ 3. 12:20:32 AM Commercials   -  Screaming Trees - Shadow Of The Season
```

Plex activity log
```
12:00am Moe Fwacky started playing The Boondocks - The Itis on RasPlex.
12:20am Moe Fwacky started playing subaru-justy-1987 on RasPlex.
12:20am Moe Fwacky started playing subaru-justy-1987 on RasPlex.
12:24am Moe Fwacky started playing Screaming Trees - Shadow Of The Season on RasPlex. (after channel restart)
```

**Comment by justinemter** [comment]
That is interesting. I'm not sure if it's related but I've had an issue over the past few days where when the pseudo-channel runs its nightly update, but it doesn't clear out the previous day...so I end up with twice as many entries. The effect of this is that the schedule gets wacky and you have all your entries from last night + today. Seems different than the issue you're presenting but wanted to bring it up.

**Comment by justinemter** [comment]
I have a feeling that some fixes I made in the "custom-section-names" branch fixed other things, like this issue.
